language: cpp

env:

compiler:
  - gcc

before_script:

script: "cd src && make -f makefile.unix test"

branches:
  only:
    - master
    - feature/travis_ci

install:
  - sudo apt-get install build-essential pkg-config
  - sudo apt-get install libtool autotools-dev autoconf
  - sudo apt-get install libssl-dev
  - sudo apt-get install libdb5.1-dev
  - sudo apt-get install libdb5.1++-dev
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install libminiupnpc-dev
notifications:
  recipients:
    - project_mail_address@gmail.com
  email:
    on_success: change
    on_failure: always

